In [335]:
import pandas as pd
import numpy as np

In [336]:
data = pd.read_csv('bollywood_full_1950-2019.csv')
data

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112.0,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73.0,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549.0,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891.0,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280.0,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4325,Samadhi (1950 film),tt0268614,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Samadhi_(1950_film),Samadhi,Samadhi,0,1950,165,Drama,6.1,21.0,The story is based on the true incident at INA...,The story is based on the true incident at INA...,NaN,Ashok Kumar|Nalini Jaywant|Kuldip Kaur|Shyam|M...,NaN,NaN
4326,Sangram (1950 film),tt0244182,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Sangram_(1950_film),Sangram,Sangram,0,1950,139,Drama,6.2,20.0,After the death of his wife a policeman fails...,After the death of his wife a policeman fails...,NaN,Ashok Kumar|Nalini Jaywant|Nawab|Sajjan|Tiwari...,NaN,NaN
4327,Sargam (1950 film),tt0269826,NaN,https://en.wikipedia.org/wiki/Sargam_(1950_film),Melody,Sargam,0,1950,135,Drama|Family,6.8,21.0,NaN,Add a Plot »,NaN,Raj Kapoor|Rehana|Om Prakash|David Abraham|Rad...,NaN,4 February 1957 (Iran)
4328,Sheesh Mahal (1950 film),tt0243555,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Sheesh_Mahal_(19...,Sheesh Mahal,Sheesh Mahal,0,1950,144,Drama,7.0,13.0,Thakur Jaspal Singh lives in the prestigious a...,Thakur Jaspal Singh lives in the prestigious a...,NaN,Sohrab Modi|Naseem Banu|Pushpa Hans|Nigar Sult...,NaN,NaN
4329,Meena Bazaar (film),tt0213081,NaN,https://en.wikipedia.org/wiki/Meena_Bazaar_(19...,Meena Bazaar,Meena Bazaar,0,1950,\N,Drama,7.0,9.0,NaN,Add a Plot »,NaN,NaN,NaN,NaN

In [337]:
data.columns

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='object')

In [338]:
from imdb import IMDb
# create an instance of the IMDb class
ia = IMDb()

In [339]:
data.dtypes

title_x              object
imdb_id              object
poster_path          object
wiki_link            object
title_y              object
original_title       object
is_adult              int64
year_of_release      object
runtime              object
genres               object
imdb_rating         float64
imdb_votes          float64
story                object
summary              object
tagline              object
actors               object
wins_nominations     object
release_date         object
dtype: object

In [340]:
from imdb import IMDb
ia = IMDb()

In [341]:
data['imdb_id'] = data['imdb_id'].str.replace('tt', '0')
data['imdb_id']

0       08291224
1       09472208
2       06986710
3       08108208
4       06028796
          ...
4325    00268614
4326    00244182
4327    00269826
4328    00243555
4329    00213081
Name: imdb_id, Length: 4330, dtype: object

In [342]:
new = data['actors'].str.split("|", n=1, expand=True)

In [343]:
data['actor_1_name'] = new[0]

In [344]:
data['actor_2'] = new[1]

In [345]:
new1 = data['actor_2'].str.split("|", n=1, expand=True)

In [346]:
data['actor_2_name'] = new1[0]

In [347]:
data['actor_3'] = new1[1]

In [348]:
new2 = data['actor_3'].str.split("|", n=1, expand=True)

In [349]:
data['actor_3_name'] = new2[0]

In [350]:
data

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,...,summary,tagline,actors,wins_nominations,release_date,actor_1_name,actor_2,actor_2_name,actor_3,actor_3_name
0,Uri: The Surgical Strike,08291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA),Vicky Kaushal,Paresh Rawal|Mohit Raina|Yami Gautam|Kirti Kul...,Paresh Rawal,Mohit Raina|Yami Gautam|Kirti Kulhari|Rajit Ka...,Mohit Raina
1,Battalion 609,09472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India),Vicky Ahuja,Shoaib Ibrahim|Shrikant Kamat|Elena Kazan|Vish...,Shoaib Ibrahim,Shrikant Kamat|Elena Kazan|Vishwas Kini|Major ...,Shrikant Kamat
2,The Accidental Prime Minister (film),06986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA),Anupam Kher,Akshaye Khanna|Aahana Kumra|Atul Sharma|Manoj ...,Akshaye Khanna,Aahana Kumra|Atul Sharma|Manoj Anand|Arjun Mat...,Aahana Kumra
3,Why Cheat India,08108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA),Emraan Hashmi,Shreya Dhanwanthary|Snighdadeep Chatterji|Navn...,Shreya Dhanwanthary,Snighdadeep Chatterji|Navneet Srivastava|Nanda...,Snighdadeep Chatterji
4,Evening Shadows,06028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India),Mona Ambegaonkar,Ananth Narayan Mahadevan|Devansh Doshi|Arpit C...,Ananth Narayan Mahadevan,Devansh Doshi|Arpit Chaudhary|Yamini Singh|Abh...,Devansh Doshi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4325,Samadhi (1950 film),00268614,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Samadhi_(1950_film),Samadhi,Samadhi,0,1950,165,Drama,...,The story is based on the true incident at INA...,NaN,Ashok Kumar|Nalini Jaywant|Kuldip Kaur|Shyam|M...,NaN,NaN,Ashok Kumar,Nalini Jaywant|Kuldip Kaur|Shyam|Mubarak|S.L. ...,Nalini Jaywant,Kuldip Kaur|Shyam|Mubarak|S.L. Puri|Badri Pras...,Kuldip Kaur
4326,Sangram (1950 film),00244182,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Sangram_(1950_film),Sangram,Sangram,0,1950,139,Drama,...,After the death of his wife a policeman fails...,NaN,Ashok Kumar|Nalini Jaywant|Nawab|Sajjan|Tiwari...,NaN,NaN,Ashok Kumar,Nalini Jaywant|Nawab|Sajjan|Tiwari|Hemavathi|S...,Nalini Jaywant,Nawab|Sajjan|Tiwari|Hemavathi|S.N. Banerjee|Ku...,Nawab
4327,Sargam (1950 film),00269826,NaN,https://en.wikipedia.org/wiki/Sargam_(1950_film),Melody,Sargam,0,1950,135,Drama|Family,...,Add a Plot »,NaN,Raj Kapoor|Rehana|Om Prakash|David Abraham|Rad...,NaN,4 February 1957 (Iran),Raj Kapoor,Rehana|Om Prakash|David Abraham|Radhakrishan|T...,Rehana,Om Prakash|David Abraham|Radhakrishan|Tabassum|,Om Prakash
4328,Sheesh Mahal (1950 film),00243555,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Sheesh_Mahal_(19...,Sheesh Mahal,Sheesh Mahal,0,1950,144,Drama,...,Thakur Jaspal Singh lives in the prestigious a...,NaN,Sohrab Modi|Naseem Banu|Pushpa Hans|Nigar Sult...,NaN,NaN,Sohrab Modi,Naseem Banu|Pushpa Hans|Nigar Sultana|Mubarak|...,Naseem Banu,Pushpa Hans|Nigar Sultana|Mubarak|Pran|Amarnat...,Pushpa Hans
4329,Meena Bazaar (film),00213081,NaN,https://en.wikipedia.org/wiki/Meena_Bazaar_(19...,Meena Bazaar,Meena Bazaar,0,1950,\N,Drama,...,Add a Plot »,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [351]:
data = data[['original_title', 'actor_1_name', 'actor_2_name', 'actor_3_name', 'genres']]

In [352]:
data

,original_title,actor_1_name,actor_2_name,actor_3_name,genres
0,Uri: The Surgical Strike,Vicky Kaushal,Paresh Rawal,Mohit Raina,Action|Drama|War
1,Battalion 609,Vicky Ahuja,Shoaib Ibrahim,Shrikant Kamat,War
2,The Accidental Prime Minister,Anupam Kher,Akshaye Khanna,Aahana Kumra,Biography|Drama
3,Why Cheat India,Emraan Hashmi,Shreya Dhanwanthary,Snighdadeep Chatterji,Crime|Drama
4,Evening Shadows,Mona Ambegaonkar,Ananth Narayan Mahadevan,Devansh Doshi,Drama
...,...,...,...,...,...
4325,Samadhi,Ashok Kumar,Nalini Jaywant,Kuldip Kaur,Drama
4326,Sangram,Ashok Kumar,Nalini Jaywant,Nawab,Drama
4327,Sargam,Raj Kapoor,Rehana,Om Prakash,Drama|Family
4328,Sheesh Mahal,Sohrab Modi,Naseem Banu,Pushpa Hans,Drama
4329,Meena Bazaar,NaN,NaN,NaN,Drama

In [353]:
data['genres'] = data['genres'].str.replace('|', ' ')

C:\Users\SADIA SUMAN-PC\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [354]:
data.rename(columns={'original_title' : 'movie_title'}, inplace=True)

C:\Users\SADIA SUMAN-PC\anaconda3\lib\site-packages\pandas\core\frame.py:4133: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [355]:
data

,movie_title,actor_1_name,actor_2_name,actor_3_name,genres
0,Uri: The Surgical Strike,Vicky Kaushal,Paresh Rawal,Mohit Raina,Action Drama War
1,Battalion 609,Vicky Ahuja,Shoaib Ibrahim,Shrikant Kamat,War
2,The Accidental Prime Minister,Anupam Kher,Akshaye Khanna,Aahana Kumra,Biography Drama
3,Why Cheat India,Emraan Hashmi,Shreya Dhanwanthary,Snighdadeep Chatterji,Crime Drama
4,Evening Shadows,Mona Ambegaonkar,Ananth Narayan Mahadevan,Devansh Doshi,Drama
...,...,...,...,...,...
4325,Samadhi,Ashok Kumar,Nalini Jaywant,Kuldip Kaur,Drama
4326,Sangram,Ashok Kumar,Nalini Jaywant,Nawab,Drama
4327,Sargam,Raj Kapoor,Rehana,Om Prakash,Drama Family
4328,Sheesh Mahal,Sohrab Modi,Naseem Banu,Pushpa Hans,Drama
4329,Meena Bazaar,NaN,NaN,NaN,Drama

In [356]:
data['movie_title'] = data['movie_title'].str.lower()

C:\Users\SADIA SUMAN-PC\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [357]:
data

,movie_title,actor_1_name,actor_2_name,actor_3_name,genres
0,uri: the surgical strike,Vicky Kaushal,Paresh Rawal,Mohit Raina,Action Drama War
1,battalion 609,Vicky Ahuja,Shoaib Ibrahim,Shrikant Kamat,War
2,the accidental prime minister,Anupam Kher,Akshaye Khanna,Aahana Kumra,Biography Drama
3,why cheat india,Emraan Hashmi,Shreya Dhanwanthary,Snighdadeep Chatterji,Crime Drama
4,evening shadows,Mona Ambegaonkar,Ananth Narayan Mahadevan,Devansh Doshi,Drama
...,...,...,...,...,...
4325,samadhi,Ashok Kumar,Nalini Jaywant,Kuldip Kaur,Drama
4326,sangram,Ashok Kumar,Nalini Jaywant,Nawab,Drama
4327,sargam,Raj Kapoor,Rehana,Om Prakash,Drama Family
4328,sheesh mahal,Sohrab Modi,Naseem Banu,Pushpa Hans,Drama
4329,meena bazaar,NaN,NaN,NaN,Drama

In [358]:
data['comb'] = data['actor_1_name'] + ' ' + data['actor_2_name'] + ' '+ data['actor_3_name'] + ' ' + data['genres']

C:\Users\SADIA SUMAN-PC\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [359]:
data

,movie_title,actor_1_name,actor_2_name,actor_3_name,genres,comb
0,uri: the surgical strike,Vicky Kaushal,Paresh Rawal,Mohit Raina,Action Drama War,Vicky Kaushal Paresh Rawal Mohit Raina Action ...
1,battalion 609,Vicky Ahuja,Shoaib Ibrahim,Shrikant Kamat,War,Vicky Ahuja Shoaib Ibrahim Shrikant Kamat War
2,the accidental prime minister,Anupam Kher,Akshaye Khanna,Aahana Kumra,Biography Drama,Anupam Kher Akshaye Khanna Aahana Kumra Biogra...
3,why cheat india,Emraan Hashmi,Shreya Dhanwanthary,Snighdadeep Chatterji,Crime Drama,Emraan Hashmi Shreya Dhanwanthary Snighdadeep ...
4,evening shadows,Mona Ambegaonkar,Ananth Narayan Mahadevan,Devansh Doshi,Drama,Mona Ambegaonkar Ananth Narayan Mahadevan Deva...
...,...,...,...,...,...,...
4325,samadhi,Ashok Kumar,Nalini Jaywant,Kuldip Kaur,Drama,Ashok Kumar Nalini Jaywant Kuldip Kaur Drama
4326,sangram,Ashok Kumar,Nalini Jaywant,Nawab,Drama,Ashok Kumar Nalini Jaywant Nawab Drama
4327,sargam,Raj Kapoor,Rehana,Om Prakash,Drama Family,Raj Kapoor Rehana Om Prakash Drama Family
4328,sheesh mahal,Sohrab Modi,Naseem Banu,Pushpa Hans,Drama,Sohrab Modi Naseem Banu Pushpa Hans Drama
4329,meena bazaar,NaN,NaN,NaN,Drama,NaN

In [360]:
data.isna().sum()

movie_title      0
actor_1_name    10
actor_2_name    10
actor_3_name    56
genres           0
comb            56
dtype: int64

In [361]:
data = data.replace(np.nan, 'unknown')

In [362]:
data

,movie_title,actor_1_name,actor_2_name,actor_3_name,genres,comb
0,uri: the surgical strike,Vicky Kaushal,Paresh Rawal,Mohit Raina,Action Drama War,Vicky Kaushal Paresh Rawal Mohit Raina Action ...
1,battalion 609,Vicky Ahuja,Shoaib Ibrahim,Shrikant Kamat,War,Vicky Ahuja Shoaib Ibrahim Shrikant Kamat War
2,the accidental prime minister,Anupam Kher,Akshaye Khanna,Aahana Kumra,Biography Drama,Anupam Kher Akshaye Khanna Aahana Kumra Biogra...
3,why cheat india,Emraan Hashmi,Shreya Dhanwanthary,Snighdadeep Chatterji,Crime Drama,Emraan Hashmi Shreya Dhanwanthary Snighdadeep ...
4,evening shadows,Mona Ambegaonkar,Ananth Narayan Mahadevan,Devansh Doshi,Drama,Mona Ambegaonkar Ananth Narayan Mahadevan Deva...
...,...,...,...,...,...,...
4325,samadhi,Ashok Kumar,Nalini Jaywant,Kuldip Kaur,Drama,Ashok Kumar Nalini Jaywant Kuldip Kaur Drama
4326,sangram,Ashok Kumar,Nalini Jaywant,Nawab,Drama,Ashok Kumar Nalini Jaywant Nawab Drama
4327,sargam,Raj Kapoor,Rehana,Om Prakash,Drama Family,Raj Kapoor Rehana Om Prakash Drama Family
4328,sheesh mahal,Sohrab Modi,Naseem Banu,Pushpa Hans,Drama,Sohrab Modi Naseem Banu Pushpa Hans Drama
4329,meena bazaar,unknown,unknown,unknown,Drama,unknown

In [363]:
old = pd.read_csv('main_data.csv')
old

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb,Genre
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...,NaN
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...,NaN
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...,NaN
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...,NaN
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...,NaN
...,...,...,...,...,...,...,...,...
6011,Joseph Kosinski,Tom Cruise,Miles Teller,Jennifer Connelly,NaN,top gun: maverick,Tom Cruise Miles Teller Jennifer Connelly Jose...,Action Drama
6012,Joel Crawford,Nicolas Cage,Emma Stone,Ryan Reynolds,NaN,the croods 2,Nicolas Cage Emma Stone Ryan Reynolds Joel Cra...,Animation Adventure Family
6013,Liesl Tommy,Jennifer Hudson,Forest Whitaker,Marlon Wayans,NaN,respect,Jennifer Hudson Forest Whitaker Marlon Wayans ...,Music Drama
6014,Ridley Scott,Matt Damon,Adam Driver,Jodie Comer,NaN,the last duel,Matt Damon Adam Driver Jodie Comer Ridley Scot...,Drama
6015,Paul Greengrass,Tom Hanks,Helena Zengel,Neil Sandilands,NaN,news of the world,Tom Hanks Helena Zengel Neil Sandilands Paul G...,Drama Western

In [364]:
old = old.drop(columns=['Genre'])
old

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
6011,Joseph Kosinski,Tom Cruise,Miles Teller,Jennifer Connelly,NaN,top gun: maverick,Tom Cruise Miles Teller Jennifer Connelly Jose...
6012,Joel Crawford,Nicolas Cage,Emma Stone,Ryan Reynolds,NaN,the croods 2,Nicolas Cage Emma Stone Ryan Reynolds Joel Cra...
6013,Liesl Tommy,Jennifer Hudson,Forest Whitaker,Marlon Wayans,NaN,respect,Jennifer Hudson Forest Whitaker Marlon Wayans ...
6014,Ridley Scott,Matt Damon,Adam Driver,Jodie Comer,NaN,the last duel,Matt Damon Adam Driver Jodie Comer Ridley Scot...
6015,Paul Greengrass,Tom Hanks,Helena Zengel,Neil Sandilands,NaN,news of the world,Tom Hanks Helena Zengel Neil Sandilands Paul G...

In [365]:
old = old.replace(np.nan, 'unknown')
old

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
6011,Joseph Kosinski,Tom Cruise,Miles Teller,Jennifer Connelly,unknown,top gun: maverick,Tom Cruise Miles Teller Jennifer Connelly Jose...
6012,Joel Crawford,Nicolas Cage,Emma Stone,Ryan Reynolds,unknown,the croods 2,Nicolas Cage Emma Stone Ryan Reynolds Joel Cra...
6013,Liesl Tommy,Jennifer Hudson,Forest Whitaker,Marlon Wayans,unknown,respect,Jennifer Hudson Forest Whitaker Marlon Wayans ...
6014,Ridley Scott,Matt Damon,Adam Driver,Jodie Comer,unknown,the last duel,Matt Damon Adam Driver Jodie Comer Ridley Scot...
6015,Paul Greengrass,Tom Hanks,Helena Zengel,Neil Sandilands,unknown,news of the world,Tom Hanks Helena Zengel Neil Sandilands Paul G...

In [366]:
final = old.append(data, ignore_index=True)
final

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
10341,NaN,Ashok Kumar,Nalini Jaywant,Kuldip Kaur,Drama,samadhi,Ashok Kumar Nalini Jaywant Kuldip Kaur Drama
10342,NaN,Ashok Kumar,Nalini Jaywant,Nawab,Drama,sangram,Ashok Kumar Nalini Jaywant Nawab Drama
10343,NaN,Raj Kapoor,Rehana,Om Prakash,Drama Family,sargam,Raj Kapoor Rehana Om Prakash Drama Family
10344,NaN,Sohrab Modi,Naseem Banu,Pushpa Hans,Drama,sheesh mahal,Sohrab Modi Naseem Banu Pushpa Hans Drama
10345,NaN,unknown,unknown,unknown,Drama,meena bazaar,unknown

In [367]:
final = final.replace(np.nan, 'unknown')
final

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
10341,unknown,Ashok Kumar,Nalini Jaywant,Kuldip Kaur,Drama,samadhi,Ashok Kumar Nalini Jaywant Kuldip Kaur Drama
10342,unknown,Ashok Kumar,Nalini Jaywant,Nawab,Drama,sangram,Ashok Kumar Nalini Jaywant Nawab Drama
10343,unknown,Raj Kapoor,Rehana,Om Prakash,Drama Family,sargam,Raj Kapoor Rehana Om Prakash Drama Family
10344,unknown,Sohrab Modi,Naseem Banu,Pushpa Hans,Drama,sheesh mahal,Sohrab Modi Naseem Banu Pushpa Hans Drama
10345,unknown,unknown,unknown,unknown,Drama,meena bazaar,unknown

In [368]:
final.to_csv('main_data1.csv')